### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by cedriccheah** [ducphu0ng/imap-netflix-household-automation#1]
Hello, I just found this and setting it up at my Synology Docker.
I facing error with Invalid credentials.
Detail:
host: imap.gmail.com
Port: 993
User: [myemail@gmail.com]
Password: [my gmail password]

<html>
<body>

date | stream | content
-- | -- | --
2024/11/16 22:09:23 | stdout | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2024/11/16 22:09:23 | stderr | error Command failed with exit code 1.
2024/11/16 22:09:23 | stderr | Node.js v20.12.2
2024/11/16 22:09:23 | stderr |  
2024/11/16 22:09:23 | stderr | at Parser._parse (/app/node_modules/imap/lib/Parser.js:139:16)
2024/11/16 22:09:23 | stderr | at Parser._resTagged (/app/node_modules/imap/lib/Parser.js:175:10)
2024/11/16 22:09:23 | stderr | at Parser.emit (node:events:518:28)
2024/11/16 22:09:23 | stderr | at Parser.<anonymous> (/app/node_modules/imap/lib/Connection.js:194:10)
2024/11/16 22:09:23 | stderr | at Connection._resTagged (/app/node_modules/imap/lib/Connection.js:1535:22)
2024/11/16 22:09:23 | stderr | at Connection.checkCaps (/app/node_modules/imap/lib/Connection.js:1635:22)
2024/11/16 22:09:23 | stderr | at reentry (/app/node_modules/imap/lib/Connection.js:1610:12)
2024/11/16 22:09:23 | stderr | at Connection.emit (node:events:518:28)
2024/11/16 22:09:23 | stderr | at Object.onceWrapper (node:events:633:26)
2024/11/16 22:09:23 | stderr | at Connection.<anonymous> (/app/src/index.ts:88:11)
2024/11/16 22:09:23 | stderr | Errorlogger: Saturday, November 16, 2024 at 2:09:23 PM UTC \| make sure you E-Mail Provider enabled IMAP and you IMAP Username and Password are correct: Error: Invalid credentials (Failure)
2024/11/16 22:09:23 | stderr |  
2024/11/16 22:09:23 | stderr |  
2024/11/16 22:09:23 | stderr | ^
2024/11/16 22:09:23 | stderr | throw new Errorlogger(`make sure you E-Mail Provider enabled IMAP and you IMAP Username and Password are correct: ${err}`);
2024/11/16 22:09:23 | stderr | /app/src/index.ts:88
2024/11/16 22:09:23 | stdout | at Parser._parse (/app/node_modules/imap/lib/Parser.js:139:16)
2024/11/16 22:09:23 | stdout | at Parser._resTagged (/app/node_modules/imap/lib/Parser.js:175:10)
2024/11/16 22:09:23 | stdout | at Parser.emit (node:events:518:28)
2024/11/16 22:09:23 | stdout | at Parser.<anonymous> (/app/node_modules/imap/lib/Connection.js:194:10)
2024/11/16 22:09:23 | stdout | at Connection._resTagged (/app/node_modules/imap/lib/Connection.js:1535:22)
2024/11/16 22:09:23 | stdout | at Connection.checkCaps (/app/node_modules/imap/lib/Connection.js:1635:22)
2024/11/16 22:09:23 | stdout | at reentry (/app/node_modules/imap/lib/Connection.js:1610:12)
2024/11/16 22:09:23 | stdout | at Connection.emit (node:events:518:28)
2024/11/16 22:09:23 | stdout | at Object.onceWrapper (node:events:633:26)
2024/11/16 22:09:23 | stdout | at Connection.<anonymous> (/app/src/index.ts:88:11)
2024/11/16 22:09:23 | stdout | Errorlogger: Saturday, November 16, 2024 at 2:09:23 PM UTC \| make sure you E-Mail Provider enabled IMAP and you IMAP Username and Password are correct: Error: Invalid credentials (Failure)
2024/11/16 22:09:20 | stdout | $ tsc --noEmit && tsx --import=extensionless/register src/index.ts
2024/11/16 22:09:20 | stdout | yarn run v1.22.22
2024/11/16 22:09:20 | stdout | Done in 0.07s.
2024/11/16 22:09:20 | stdout | success Already up-to-date.
2024/11/16 22:09:20 | stdout | [1/4] Resolving packages...
2024/11/16 22:09:20 | stdout | yarn install v1.22.22

</body>
</html>

**Comment by ducphu0ng** [comment]
Hi!

Make sure you have enabled IMAP in your Gmail settings, as this is necessary for the connection you can find Details here for Google:
https://github.com/ducphu0ng/imap-netflix-household-automation?tab=readme-ov-file#prerequisites.

The error indicates that either the IMAP server is not active or your credentials are incorrect. I don’t know the details of your Gmail password, but usually, to connect to Gmail, you need an **App Password**, which is different from your regular Gmail password, to allow third-party software to connect to Google’s IMAP server.

To generate an **App Password:**

Enable 2-Step Verification in your Google account. You can find this under **Settings -> Security**, and then configure **2-Step Verification**.
Once 2-Step Verification is enabled, search for "**App Passwords**" in your Google account settings.
Create an App Password, and use it instead of your normal Gmail password when connecting to the IMAP server.

**Comment by cedriccheah** [comment]
Hi @ducphu0ng 

Really appreciate your details step on App Password and this resolved my issue.
Will monitor if this working as expected.

> 024/11/18 17:38:15 | stdout | IMAP connection is ready, start listening Emails on INBOX
> 2024/11/18 17:38:09 | stdout | $ tsc --noEmit && tsx --import=extensionless/register src/index.ts
> 2024/11/18 17:38:09 | stdout | yarn run v1.22.22
> 2024/11/18 17:38:08 | stdout | Done in 0.30s.
> 2024/11/18 17:38:08 | stdout | success Already up-to-date.
> 2024/11/18 17:38:08 | stdout | [1/4] Resolving packages...
> 2024/11/18 17:38:08 | stdout | yarn install v1.22.22

Thank you!
