### ISSUE TITLE
New device email on each approval

### ISSUE THREAD

**Issue by FrancYescO** [ducphu0ng/imap-netflix-household-automation#2]
Can we avoid to get an email about new device (i assume the newly spawned headless "Chrome - Browser web") is using Netflix each time an approval is made?

Maybe storing session cookie is enough

**Comment by ducphu0ng** [comment]
Hi @FrancYescO,

Sure, we can store the session/cookie for next time. It seems like Netflix has made some internal changes and is now sending emails about newly added devices. Please refer to the PR above.

Let me know if this helps!

**Comment by FrancYescO** [comment]
here just to confirm that the new edits are working ;)
